config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get 'login', to: 'login#index'
  resources :homes, :only => [:index]
  resources :contacts do
    resources :comments
  end
  resources :checks
  resources :memos, only: %i(index new create edit update destroy)
  devise_for :admins
  devise_for :user_officers
  devise_for :user_students
  resources :user_students, only: [:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user_student.rb
class UserStudent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :student_id,
            presence: true, uniqueness: true,
            numericality: { only_integer: true, greater_than: 0 }
  validates :school_id,
            presence: true,
            numericality: { only_integer: true, greater_than: 0 }
  validates :birth_date, presence: true
  validates :grade, presence: true
  validates :blood_type, presence: true

  enum grade: {小学1年生:1,
               小学2年生:2,
               小学3年生:3,
               小学4年生:4,
               小学5年生:5,
               小学6年生:6,
               中学1年生:7,
               中学2年生:8,
               中学3年生:9,
               高校1年生:10,
               高校2年生:11,
               高校3年生:12
             }
   enum blood_type: {A型:0,
                    B型:1,
                    O型:2,
                    AB型:3
              }
end

app/controllers/user_students/confirmations_controller.rb
# frozen_string_literal: true

class UserStudents::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user_students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class UserStudents::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user_students/passwords_controller.rb
# frozen_string_literal: true

class UserStudents::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user_students/registrations_controller.rb
# frozen_string_literal: true

class UserStudents::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_students/sessions_controller.rb
# frozen_string_literal: true

class UserStudents::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user_students/unlocks_controller.rb
# frozen_string_literal: true

class UserStudents::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_students_controller.rb
class UserStudentsController < ApplicationController
  before_action :authenticate_user_student!

  def index
    @user_students = UserStudent.all
  end

  def show
    @checks = current_user_student.checks
    @user_student = current_user_student
    @contacts = Contact.where(user_student_id: @user_student.id).all.page(params[:page]).per(10)
    @user_student = UserStudent.find(params[:id])
    unless @user_student == current_user_student
      redirect_to homes_path, notice: '他の人のプロフィール画面へはアクセスが出来ません。'
    end
  end


end

app/helpers/user_students_helper.rb
module UserStudentsHelper
end

app/views/user_students/show.html.erb
<div class="mx-auto p-4 border border-info rounded" style="border:solid 1px #343a40; max-width:1200px;">
  <h2 class="text-center">プロフィール画面</h2><br/>
  <br>
  <div class="row">
    <div class="float-left">
      <% if @user_student.profile_image.attached? %>
      <%= image_tag @user_student.profile_image.variant(combine_options:{gravity: :center,
                                                                        border:'2',
                                                                        resize:"200x200^",
                                                                        crop:"220x220+0+0"}).processed,
                                                                        class: "img border-info"%><br/>
      <% end %>
    </div>
    <div class="col">
      <div class="row">
        <div class="col-md-6">
          <h5>ユーザー名</h5>
          <p class="alert alert-info rounded"><%= @user_student.name %></p>
        </div>
        <div class="col-md-6">
          <h5>メールアドレス</h5>
          <p class="alert alert-info rounded"><%= @user_student.email %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h5>生徒ID</h5>
          <p class="alert alert-info rounded"><%= @user_student.student_id %></p>
        </div>
        <div class="col-md-6">
          <h5>学校ID</h5>
          <p class="alert alert-info rounded"><%= @user_student.school_id %></p>
        </div>
      </div>
      <br/>
      <hr>
      <br/>
      <div class="row">
        <div class="col-md-4">
          <h5>生年月日</h5>
          <p class="alert alert-info rounded form"><%= @user_student.birth_date %></p>
        </div>
        <div class="col-md-4">
          <h5>学年</h5>
          <p class="alert alert-info rounded form"><%= @user_student.grade %></p>
        </div>
        <div class="col-md-4">
          <h5>血液型</h5>
          <p class="alert alert-info rounded form"><%= @user_student.blood_type %></p>
        </div>
      </div>

      <br>
    </div>
  </div>
  <%= link_to "編集", edit_user_student_registration_path , class: "btn btn-info float-right"%>
  <br>
</div>


<div class="mx-auto p-4 border border-info rounded mt-3" style="border:solid 1px #343a40; max-width:1200px;">
  <h2>診断結果</h2><br/>
  <br>
  <% @checks.each do |check|%>
    <div class="col">
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-4">
          <h5>診断日</h5>
          <p class="alert alert-info rounded"><%= l check.created_at, format: :check %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h5>身長</h5>
          <p class="alert alert-info rounded"><%= check.height %></p>
        </div>
        <div class="col-md-4">
          <h5>体重</h5>
          <p class="alert alert-info rounded"><%= check.body_weight %></p>
        </div>
        <div class="col-md-4">
          <h5>座高</h5>
          <p class="alert alert-info rounded"><%= check.sitting_height %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h5>裸眼視力</h5>
          <p class="alert alert-info rounded"><%= check.naked_eyesight %></p>
        </div>
        <div class="col-md-4">
          <h5>矯正視力</h5>
          <p class="alert alert-info rounded form"><%= check.corrected_eyesight %></p>
        </div>
        <div class="col-md-4">
          <h5>聴力</h5>
          <p class="alert alert-info rounded form"><%= check.hearing %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h5>尿検査</h5>
          <p class="alert alert-info rounded form"><%= check.urine %></p>
        </div>
        <div class="col-md-4">
          <h5>心電図検査</h5>
          <p class="alert alert-info rounded form"><%= check.electro_cardiogram %></p>
        </div>
        <div class="col-md-4">
          <h5>栄養状態</h5>
          <p class="alert alert-info rounded form"><%= check.nutritional_status %></p>
        </div>
      </div>
      <br>
    </div>
  <% end %>
</div>


<div class="mx-auto p-4 border border-info rounded mt-3" style="border:solid 1px #343a40; max-width:1200px;">
  <h4><%= current_user_student.name%>さんの過去の投稿記録</h4><br/>
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |student_contact| %>
        <tr>
          <td><%= student_contact.title.truncate(15) %></td>
          <td><%= student_contact.content.truncate(15) %></td>
          <td><%= link_to 'Show', student_contact, class: "text-info" %></td>
          <td><%= link_to 'Edit', edit_contact_path(student_contact), class: "text-info" %></td>
          <td><%= link_to 'Destroy', student_contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-info" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="my-4 mx-auto" style="width: 200px;">
    <%= paginate @contacts %>
  </div>
</div>