config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get 'login', to: 'login#index'
  resources :homes, :only => [:index]
  resources :contacts do
    resources :comments
  end
  resources :checks
  resources :memos, only: %i(index new create edit update destroy)
  devise_for :admins
  devise_for :user_officers
  devise_for :user_students
  resources :user_students, only: [:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user_student
  belongs_to :user_officer


  enum hearing: {よく聞こえている:0,
               聞こえている:1,
               少し聞こえずらい:2,
               医師に相談:3
            }

  enum urine: {健康:0,
               問題なし:1,
               少し疲れあり:2,
               疲れ有り:3
            }

  enum electro_cardiogram: {異常なし:0,
                            健康上異常なし:1,
                            運動を控える:2,
                            問題あり:3
                          }

  enum nutritional_status: {充分取れている:0,
                            取れている:1,
                            少し取れている:2,
                            取れていない:3
                          }
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :authenticate_user_officer!
  before_action :set_check, only: %i(show edit update)

  def index
    @q = Check.page(params[:page]).per(10).ransack(params[:q])
    @checks = @q.result(distinct: true).includes(:user_student)
  end

  def new
    @check = current_user_officer.checks.build
  end

  def create
    @check = current_user_officer.checks.build(check_params)
    if @check.save
      redirect_to checks_path, notice: "Successfully saved."
    else
      render :new
    end
  end

  def show
  end

  def update
    if @check.update(check_params)
      redirect_to checks_path, notice: 'Successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @check.destroy
    redirect_to check_path, notice: 'Successfully destroyed.'
  end



  private

  def set_check
    @check = Check.find(params[:id])
  end

  def check_params
    params.require(:check).permit %i(height body_weight sitting_height naked_eyesight corrected_eyesight hearing urine electro_cardiogram nutritional_status user_student_id )
  end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_with(model: check, local: true) do |f| %>

  <div class="m-4 p-2">
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :user_student %>
        <%= f.collection_select :user_student_id, UserStudent.all, :id, :name,{prompt: "選択してください"}, {class: "form-control"} %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :school_id %>
        <%= f.collection_select :school_id, UserStudent.all, :id, :school_id,{prompt: "選択してください"}, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :height %>
        <%= f.text_field :height, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= f.label :body_weight %>
        <%= f.text_field :body_weight, autofocus: true, class: "form-control"%>
      </div>

      <div class="form-group col-md-4">
        <%= f.label :sitting_height %>
        <%= f.text_field :sitting_height, autofocus: true, class: "form-control"%>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :naked_eyesight %>
        <%= f.text_field :naked_eyesight, autofocus: true, class: "form-control"%>
      </div>

      <div class="form-group col-md-6">
        <%= f.label :corrected_eyesight %>
        <%= f.text_field :corrected_eyesight, autofocus: true, class: "form-control"%>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :hearing %><br />
        <%= f.select :hearing, {よく聞こえている: 'よく聞こえている',
                                聞こえている: '聞こえている',
                                少し聞こえずらい: '少し聞こえずらい',
                                医師に相談: '医師に相談',
                          },
                          { include_blank: '段階選択'},
                          {  class: "form-control", required: true }
        %>
      </div>
    </div>

    <div class="form-row" style="padding-bottom:2.5rem;">
      <% if user_officer_signed_in? && current_user_officer.type == '医師'%>
        <div class="form-group col-md-4">
          <%= f.label :urine %><br />
          <%= f.select :urine, {健康: '健康',
                                問題なし: '問題なし',
                                少し疲れあり: '少し疲れあり',
                                疲れ有り: '3',
                            },
                            { include_blank: '段階選択'},
                            {  class: "form-control", required: true }
          %>
        </div>

        <div class="form-group col-md-4">
          <%= f.label :electro_cardiogram %><br />
          <%= f.select :electro_cardiogram, {異常なし: '異常なし',
                                             健康上異常なし: '健康上異常なし',
                                             運動を控える: '運動を控える',
                                             問題あり: '問題あり',
                                          },
                                          { include_blank: '段階選択'},
                                          {  class: "form-control", required: true }
          %>
        </div>


        <div class="form-group col-md-4">
          <%= f.label :nutritional_status %><br />
          <%= f.select :nutritional_status, {充分取れている: '充分取れている',
                                             取れている: '取れている',
                                             少し取れている: '少し取れている',
                                             取れていない: '取れていない',
                                          },
                                          { include_blank: '段階選択'},
                                          {  class: "form-control", required: true }
          %>
        </div>
      <% end %>
    </div>

    <div class="form-row">
      <div class="col">
        <%= f.submit "送信", class: "btn btn-info form-control" %>
      </div>
      <div class="col">
        <%= link_to "戻る", checks_path, class: "btn btn-outline-info form-control" %>
      </div>
    </div>
  </div>
<% end %>

app/views/checks/edit.html.erb
<div class="card mx-auto p-2 border border-info rounded" style="max-width:700px;">

  <h2 class="mx-4 p-2">投稿編集</h2>

  <%= render "form", check: @check %>
</div>

app/views/checks/index.html.erb
<h1>生徒診断情報一覧</h1>

<%= link_to 'New contact', new_check_path, class: "btn btn-info float-right" %>

<div>
  <%= search_form_for @q do |f| %>
    <div class="input-group">
      <%= f.search_field :user_student_name_cont, class: "form-control offset-sm-8", placeholder: "ユーザ検索" %>
      <%= button_tag type: "submit", class: "input-group-append input-group-text" do %>
          <i class="fas fa-search"></i>
        <% end %>
    </div>
  <% end %>
</div>


  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>User_Student</th>
        <th>Compreated_at</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @checks.each do |check| %>
        <tr>
          <td><%= check.user_student.name.truncate(15) %></td>
          <td><%= l check.created_at, format: :check %></td>
          <td><%= link_to 'Show', check_path(check), class: "text-info" %></td>
          <td><%= link_to 'Edit', edit_check_path(check), class: "text-info" %></td>
          <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-info" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @checks %>

app/views/checks/new.html.erb
<div class="card mx-auto p-3 border border-info rounded" style="max-width:700px; padding-bottom:4.5rem;">

  <h2 class="mx-4 p-2">診断結果記入フォーム</h2>

  <%= render "form", check: @check %>
</div>

app/views/checks/show.html.erb
<div class="mx-auto p-4 border border-info rounded" style="border:solid 1px #343a40; max-width:1200px;">
  <h2 class="text-center">診断結果画面</h2><br/>
  <div class="col">
    <div class="row">
      <div class="col-md-9"></div>
      <div class="col-md-3">
        <h5>診断日</h5>
        <p class="alert alert-primary rounded"><%= l @check.created_at, format: :check %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h5>生徒名</h5>
        <p class="alert alert-info rounded"><%= @check.user_student.name %></p>
      </div>
      <div class="col-md-6">
        <h5>学校ID</h5>
        <p class="alert alert-info rounded"><%= @check.user_student.school_id %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <h5>身長</h5>
        <p class="alert alert-info rounded"><%= @check.height %></p>
      </div>
      <div class="col-md-4">
        <h5>体重</h5>
        <p class="alert alert-info rounded"><%= @check.body_weight %></p>
      </div>
      <div class="col-md-4">
        <h5>座高</h5>
        <p class="alert alert-info rounded"><%= @check.sitting_height %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <h5>裸眼視力</h5>
        <p class="alert alert-info rounded"><%= @check.naked_eyesight %></p>
      </div>
      <div class="col-md-4">
        <h5>矯正視力</h5>
        <p class="alert alert-info rounded form"><%= @check.corrected_eyesight %></p>
      </div>
      <div class="col-md-4">
        <h5>聴力</h5>
        <p class="alert alert-info rounded form"><%= @check.hearing %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <h5>尿検査</h5>
        <p class="alert alert-info rounded form"><%= @check.urine %></p>
      </div>
      <div class="col-md-4">
        <h5>心電図検査</h5>
        <p class="alert alert-info rounded form"><%= @check.electro_cardiogram %></p>
      </div>
      <div class="col-md-4">
        <h5>血液型</h5>
        <p class="alert alert-info rounded form"><%= @check.nutritional_status %></p>
      </div>
    </div>
    <br>
  </div>
</div>