config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get 'login', to: 'login#index'
  resources :homes, :only => [:index]
  resources :contacts do
    resources :comments
  end
  resources :checks
  resources :memos, only: %i(index new create edit update destroy)
  devise_for :admins
  devise_for :user_officers
  devise_for :user_students
  resources :user_students, only: [:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalMgtForStudents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav">
            <%= link_to  homes_path, method: :get do %>
              <i class="btn btn-info fas fa-laptop-medical fa-3x"></i>
            <% end %>
            <% if user_student_signed_in? %>
              <li class="nav-item active nav-link ml-3 mt-2 mr-3">
                <%= current_user_student.name %>さん
              </li>
              <li class="nav-item active mt-2 mr-3">
                <%= link_to "ログアウト", destroy_user_student_session_path, method: :delete , class: 'nav-link'%>
              </li>
            <% elsif user_officer_signed_in? %>
              <li class="nav-item active nav-link ml-3 mt-2 mr-3">
                <%= current_user_officer.name %>さん
              </li>
              <li class="nav-item active mt-2">
                <%= link_to "ログアウト", destroy_user_officer_session_path ,:method => :delete , class: 'nav-link'%>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item active nav-link ml-3 mt-2 mr-3">
                <%= current_admin.name %>さん
              </li>
              <li class="nav-item active mt-2">
                <%= link_to "ログアウト", destroy_admin_session_path ,:method => :delete , class: 'nav-link'%>
              </li>
            <% else %>
              <li class="nav-item active ml-3 mt-2 mr-3">
                <%= link_to "ユーザー新規登録", new_user_student_registration_path , class: 'nav-link'%>
              </li>
              <li class="nav-item active mt-2">
                <%= link_to "ログイン", new_user_student_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container" style="padding-top:4.5rem;">
      <%= yield %>
    </div>
  </body>
</html>